version: "3.3"

services:
  db:
    image: postgres:12.3
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: QSMP
      POSTGRES_PASSWORD: QSMP-2024
      POSTGRES_DB: QSMP-MUSEUM
    networks:
      - QSMP

networks:
  QSMP:
    name: QSMP
